services:
  otelcol:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.111.0
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "40318:40318"
    restart: unless-stopped
  lgtm:
    image: grafana/otel-lgtm:0.7.5
    ports:
      - "40300:3000"