receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:40318
        
exporters:
  debug:
    verbosity: normal
  otlphttp:
    endpoint: http://lgtm:4318

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug, otlphttp ]